export const TYPE_USER = [
    "PERTE_DE_POID_SPORTIF",
    "PERTE_DE_POIDS_NON_SPORTIF",
    "REALIGNEMENT_ALIMENTAIRE_SPORTIF",
    "REALIGNEMENT_ALIMENTAIRE_NON_SPORTIF",
    "PRISE_DE_MASSES_PORTIF",
    "PRISE_DE_MASSE_NON_SPORTIF"]