import type React from "react"
import type { Metadata } from "next"
import Navbar from "./navbar"
import SideBar from "./sidebar"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div className="flex h-screen">
          {/* Sidebar component */}
          <SideBar />

          {/* Right side (Navbar + Content) */}
          <div className="flex flex-col flex-1">
            {/* Navbar at the top */}
            <Navbar />

            {/* Main content below the Navbar */}
            <main className="flex-1 p-4 overflow-y-auto bg-[#F5F7FA]">{children}</main>
          </div>
        </div>

  )
}

