import type React from "react"
import type { Metadata } from "next"
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google"
import Navbar from "./navbar"
import SideBar from "./sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen">
          {/* Sidebar component */}
          <SideBar />

          {/* Right side (Navbar + Content) */}
          <div className="flex flex-col flex-1">
            {/* Navbar at the top */}
            <Navbar />

            {/* Main content below the Navbar */}
            <main className="flex-1 p-4 overflow-y-auto bg-[#F5F7FA]">{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}

