import type { Metadata } from "next";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode; // Explicitly define the type for children
}

export default function Layout({ children }: LayoutProps) {
  return (
            <main className="flex-1  overflow-y-auto bg-[#F5F7FA]">
              <div
                className="h-screen bg-center bg-no-repeat flex items-center "
                style={{ backgroundImage: `url('/images/qBg.png')` }}
              >
                <div className="container mx-auto px-4 md:px-16 lg:px-75">
                  <div className="flex flex-col items-center mb-8">
                    <Image src="/logos/meklaLogo.png" alt="Mekla Logo" width={100} height={40} />
                
                    <div className="w-full md:w-3/4 flex flex-col min-h-[300px] justify-between">
                      <div className="flex-grow w-full flex items-center justify-center">
                         {children}
                      </div>
                    </div>
                  </div>
                  </div>
              </div>
            </main>
  );
}